import type { PropertyCanonical } from '../core/canonical-schema.js';

/**
 * ダミー物件データ（Phase 1 動作確認用）
 * 東京23区の1棟不動産を模した架空データ
 */
export const dummyProperties: PropertyCanonical[] = [
  {
    canonicalId: 'dummy-001',
    propertyName: 'グランレジデンス中野',
    prefecture: '東京都',
    ward: '中野区',
    address: '東京都中野区中野5-10-1',
    lat: 35.7074,
    lng: 139.6638,
    structureType: 'W',
    builtYear: 2005,
    builtMonth: 3,
    landAreaSqm: 120,
    buildingAreaSqm: 180,
    totalFloors: 3,
    totalUnits: 9,
    roomBreakdown: '1K×9',
    occupiedUnits: 8,
    vacantUnits: 1,
    occupancyRate: 88.9,
    station1: { line: 'JR中央線', name: '中野', walkMin: 6, dailyPassengers: 140_000 },
    station2: { line: '東京メトロ東西線', name: '中野', walkMin: 6 },
    urbanPopulation: 345_000,
    propertyPriceJpy: 68_000_000,
    annualFullRentJpy: 6_480_000,
    annualCurrentRentJpy: 5_760_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 10_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 450_000,
    reBuildable: true,
    roadDirection: '南',
    roadWidth: 6.0,
    brokerName: 'サンプル不動産',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/001',
    listingId: 'RM-001',
  },
  {
    canonicalId: 'dummy-002',
    propertyName: 'メゾン・ド・品川',
    prefecture: '東京都',
    ward: '品川区',
    address: '東京都品川区西五反田3-2-5',
    lat: 35.6248,
    lng: 139.7227,
    structureType: 'RC',
    builtYear: 1995,
    builtMonth: 8,
    landAreaSqm: 150,
    buildingAreaSqm: 420,
    totalFloors: 5,
    totalUnits: 12,
    roomBreakdown: '1DK×8, 1LDK×4',
    occupiedUnits: 12,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: 'JR山手線', name: '五反田', walkMin: 8, dailyPassengers: 130_000 },
    station2: { line: '都営浅草線', name: '五反田', walkMin: 8 },
    station3: { line: '東急池上線', name: '大崎広小路', walkMin: 5 },
    urbanPopulation: 420_000,
    propertyPriceJpy: 125_000_000,
    annualFullRentJpy: 10_800_000,
    annualCurrentRentJpy: 10_800_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 20_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 700_000,
    reBuildable: true,
    roadDirection: '東',
    roadWidth: 8.0,
    brokerName: 'テスト仲介',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'athome',
    sourceUrl: 'https://example.com/athome/002',
    listingId: 'AH-002',
  },
  {
    canonicalId: 'dummy-003',
    propertyName: 'コーポ板橋',
    prefecture: '東京都',
    ward: '板橋区',
    address: '東京都板橋区板橋1-15-3',
    lat: 35.7513,
    lng: 139.7098,
    structureType: 'W',
    builtYear: 1998,
    builtMonth: 6,
    landAreaSqm: 100,
    buildingAreaSqm: 140,
    totalFloors: 2,
    totalUnits: 6,
    roomBreakdown: '1K×6',
    occupiedUnits: 5,
    vacantUnits: 1,
    occupancyRate: 83.3,
    station1: { line: 'JR埼京線', name: '板橋', walkMin: 4, dailyPassengers: 45_000 },
    station2: { line: '都営三田線', name: '新板橋', walkMin: 7 },
    urbanPopulation: 580_000,
    propertyPriceJpy: 35_000_000,
    annualFullRentJpy: 3_600_000,
    annualCurrentRentJpy: 3_000_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 5_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 320_000,
    reBuildable: true,
    roadDirection: '北',
    roadWidth: 4.5,
    brokerName: 'テスト不動産',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/003',
    listingId: 'RM-003',
  },
  {
    canonicalId: 'dummy-004',
    propertyName: 'ヴィラ新宿',
    prefecture: '東京都',
    ward: '新宿区',
    address: '東京都新宿区百人町2-5-10',
    lat: 35.6983,
    lng: 139.6986,
    structureType: 'S',
    builtYear: 2010,
    builtMonth: 11,
    landAreaSqm: 80,
    buildingAreaSqm: 200,
    totalFloors: 4,
    totalUnits: 8,
    roomBreakdown: '1K×8',
    occupiedUnits: 7,
    vacantUnits: 1,
    occupancyRate: 87.5,
    station1: { line: 'JR山手線', name: '新大久保', walkMin: 3, dailyPassengers: 95_000 },
    station2: { line: 'JR中央線', name: '大久保', walkMin: 5 },
    urbanPopulation: 350_000,
    propertyPriceJpy: 98_000_000,
    annualFullRentJpy: 8_640_000,
    annualCurrentRentJpy: 7_560_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 15_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 550_000,
    reBuildable: true,
    roadDirection: '南',
    roadWidth: 5.5,
    brokerName: 'サンプル仲介',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'athome',
    sourceUrl: 'https://example.com/athome/004',
    listingId: 'AH-004',
  },
  {
    canonicalId: 'dummy-005',
    propertyName: 'ハイツ足立',
    prefecture: '東京都',
    ward: '足立区',
    address: '東京都足立区千住3-20-8',
    lat: 35.7488,
    lng: 139.8042,
    structureType: 'W',
    builtYear: 1990,
    builtMonth: 2,
    landAreaSqm: 130,
    buildingAreaSqm: 160,
    totalFloors: 2,
    totalUnits: 8,
    roomBreakdown: '1K×8',
    occupiedUnits: 6,
    vacantUnits: 2,
    occupancyRate: 75,
    station1: { line: 'JR常磐線', name: '北千住', walkMin: 10, dailyPassengers: 210_000 },
    station2: { line: '東京メトロ千代田線', name: '北千住', walkMin: 10 },
    station3: { line: '東武スカイツリーライン', name: '北千住', walkMin: 10 },
    urbanPopulation: 690_000,
    propertyPriceJpy: 28_000_000,
    annualFullRentJpy: 4_320_000,
    annualCurrentRentJpy: 3_240_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 5_000_000,
    loanInterestPct: 1.5,
    loanYears: 25,
    roadValueJpyPerSqm: 250_000,
    reBuildable: true,
    roadDirection: '西',
    roadWidth: 5.0,
    brokerName: 'テスト不動産A',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/005',
    listingId: 'RM-005',
  },
  {
    canonicalId: 'dummy-006',
    propertyName: 'プラザ豊島',
    prefecture: '東京都',
    ward: '豊島区',
    address: '東京都豊島区南池袋2-8-12',
    lat: 35.7272,
    lng: 139.7121,
    structureType: 'RC',
    builtYear: 2000,
    builtMonth: 4,
    landAreaSqm: 90,
    buildingAreaSqm: 280,
    totalFloors: 5,
    totalUnits: 10,
    roomBreakdown: '1K×10',
    occupiedUnits: 10,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: 'JR山手線', name: '池袋', walkMin: 7, dailyPassengers: 560_000 },
    station2: { line: '東京メトロ有楽町線', name: '東池袋', walkMin: 5 },
    urbanPopulation: 300_000,
    propertyPriceJpy: 95_000_000,
    annualFullRentJpy: 7_920_000,
    annualCurrentRentJpy: 7_920_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 15_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 900_000,
    reBuildable: true,
    roadDirection: '東',
    roadWidth: 7.0,
    brokerName: 'テスト仲介B',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'athome',
    sourceUrl: 'https://example.com/athome/006',
    listingId: 'AH-006',
  },
  {
    canonicalId: 'dummy-007',
    propertyName: 'レジデンス世田谷',
    prefecture: '東京都',
    ward: '世田谷区',
    address: '東京都世田谷区三軒茶屋1-15-7',
    lat: 35.6437,
    lng: 139.6705,
    structureType: 'W劣',
    builtYear: 2012,
    builtMonth: 9,
    landAreaSqm: 110,
    buildingAreaSqm: 165,
    totalFloors: 3,
    totalUnits: 6,
    roomBreakdown: '1LDK×6',
    occupiedUnits: 6,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: '東急田園都市線', name: '三軒茶屋', walkMin: 5, dailyPassengers: 130_000 },
    station2: { line: '東急世田谷線', name: '三軒茶屋', walkMin: 4 },
    urbanPopulation: 940_000,
    propertyPriceJpy: 82_000_000,
    annualFullRentJpy: 6_840_000,
    annualCurrentRentJpy: 6_840_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 12_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 650_000,
    reBuildable: true,
    roadDirection: '南',
    roadWidth: 6.0,
    brokerName: 'テスト仲介C',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/007',
    listingId: 'RM-007',
  },
  {
    canonicalId: 'dummy-008',
    propertyName: '再建築不可アパート荒川',
    prefecture: '東京都',
    ward: '荒川区',
    address: '東京都荒川区東日暮里4-3-2',
    lat: 35.7273,
    lng: 139.7778,
    structureType: 'W',
    builtYear: 1985,
    builtMonth: 1,
    landAreaSqm: 80,
    buildingAreaSqm: 96,
    totalFloors: 2,
    totalUnits: 4,
    roomBreakdown: '1K×4',
    occupiedUnits: 3,
    vacantUnits: 1,
    occupancyRate: 75,
    station1: { line: 'JR山手線', name: '日暮里', walkMin: 12, dailyPassengers: 110_000 },
    urbanPopulation: 220_000,
    propertyPriceJpy: 18_000_000,
    annualFullRentJpy: 2_880_000,
    annualCurrentRentJpy: 2_160_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 3_000_000,
    loanInterestPct: 2.0,
    loanYears: 20,
    roadValueJpyPerSqm: 280_000,
    reBuildable: false,
    roadWidth: 1.8,
    brokerName: 'テスト不動産D',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/008',
    listingId: 'RM-008',
  },
  {
    canonicalId: 'dummy-009',
    propertyName: 'パークコート目黒',
    prefecture: '東京都',
    ward: '目黒区',
    address: '東京都目黒区中目黒2-7-15',
    lat: 35.6422,
    lng: 139.6989,
    structureType: 'RC',
    builtYear: 2008,
    builtMonth: 5,
    landAreaSqm: 140,
    buildingAreaSqm: 350,
    totalFloors: 5,
    totalUnits: 10,
    roomBreakdown: '1LDK×6, 2LDK×4',
    occupiedUnits: 9,
    vacantUnits: 1,
    occupancyRate: 90,
    station1: { line: '東急東横線', name: '中目黒', walkMin: 7, dailyPassengers: 180_000 },
    station2: { line: '東京メトロ日比谷線', name: '中目黒', walkMin: 7 },
    urbanPopulation: 285_000,
    propertyPriceJpy: 148_000_000,
    annualFullRentJpy: 11_400_000,
    annualCurrentRentJpy: 10_260_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 25_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 850_000,
    reBuildable: true,
    roadDirection: '南東',
    roadWidth: 8.0,
    brokerName: 'テスト仲介E',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'athome',
    sourceUrl: 'https://example.com/athome/009',
    listingId: 'AH-009',
  },
  {
    canonicalId: 'dummy-010',
    propertyName: 'サンハイツ北区',
    prefecture: '東京都',
    ward: '北区',
    address: '東京都北区赤羽1-22-5',
    lat: 35.7774,
    lng: 139.7206,
    structureType: 'S',
    builtYear: 2002,
    builtMonth: 10,
    landAreaSqm: 105,
    buildingAreaSqm: 210,
    totalFloors: 3,
    totalUnits: 7,
    roomBreakdown: '1K×5, 1DK×2',
    occupiedUnits: 7,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: 'JR京浜東北線', name: '赤羽', walkMin: 5, dailyPassengers: 165_000 },
    station2: { line: 'JR埼京線', name: '赤羽', walkMin: 5 },
    station3: { line: '東京メトロ南北線', name: '赤羽岩淵', walkMin: 8 },
    urbanPopulation: 355_000,
    propertyPriceJpy: 55_000_000,
    annualFullRentJpy: 5_040_000,
    annualCurrentRentJpy: 5_040_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 8_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 380_000,
    reBuildable: true,
    roadDirection: '東',
    roadWidth: 6.0,
    brokerName: 'テスト不動産F',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/010',
    listingId: 'RM-010',
  },
  {
    canonicalId: 'dummy-011',
    propertyName: 'アーバンコート杉並',
    prefecture: '東京都',
    ward: '杉並区',
    address: '東京都杉並区高円寺南4-8-3',
    lat: 35.7053,
    lng: 139.6501,
    structureType: 'W',
    builtYear: 2015,
    builtMonth: 7,
    landAreaSqm: 95,
    buildingAreaSqm: 142,
    totalFloors: 2,
    totalUnits: 6,
    roomBreakdown: '1K×4, 1LDK×2',
    occupiedUnits: 6,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: 'JR中央線', name: '高円寺', walkMin: 4, dailyPassengers: 95_000 },
    station2: { line: '東京メトロ丸ノ内線', name: '新高円寺', walkMin: 10 },
    urbanPopulation: 580_000,
    propertyPriceJpy: 72_000_000,
    annualFullRentJpy: 5_760_000,
    annualCurrentRentJpy: 5_760_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 10_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 480_000,
    reBuildable: true,
    roadDirection: '南',
    roadWidth: 5.0,
    brokerName: 'テスト仲介G',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'athome',
    sourceUrl: 'https://example.com/athome/011',
    listingId: 'AH-011',
  },
  {
    canonicalId: 'dummy-012',
    propertyName: 'シャーメゾン台東',
    prefecture: '東京都',
    ward: '台東区',
    address: '東京都台東区入谷1-5-2',
    lat: 35.7212,
    lng: 139.7870,
    structureType: 'W劣',
    builtYear: 2018,
    builtMonth: 3,
    landAreaSqm: 75,
    buildingAreaSqm: 150,
    totalFloors: 3,
    totalUnits: 9,
    roomBreakdown: '1K×9',
    occupiedUnits: 9,
    vacantUnits: 0,
    occupancyRate: 100,
    station1: { line: '東京メトロ日比谷線', name: '入谷', walkMin: 3, dailyPassengers: 30_000 },
    station2: { line: 'JR山手線', name: '鶯谷', walkMin: 8 },
    urbanPopulation: 215_000,
    propertyPriceJpy: 85_000_000,
    annualFullRentJpy: 7_020_000,
    annualCurrentRentJpy: 7_020_000,
    expenseRatioPct: 16.0,
    selfFundingJpy: 12_000_000,
    loanInterestPct: 1.5,
    loanYears: 30,
    roadValueJpyPerSqm: 520_000,
    reBuildable: true,
    roadDirection: '東',
    roadWidth: 4.5,
    brokerName: 'テスト不動産H',
    hasOccupancyInfo: true,
    hasRouteValue: true,
    hasTaxInfo: false,
    sourceSite: 'rakumachi',
    sourceUrl: 'https://example.com/rakumachi/012',
    listingId: 'RM-012',
  },
];
