-- Asahi Eiken 2 Coach - シードデータ
-- 注意: auth.users への挿入は Supabase Auth 経由で行うため、
-- ここでは grammar_cards と vocab_items のみを投入します。
-- ユーザー作成後に users テーブルの auth_id を紐付けてください。

-- ==============================
-- 文法カード (55件)
-- ==============================
INSERT INTO grammar_cards (category, front_text, back_text, explanation, difficulty, related_points) VALUES
('時制', '「私は毎日英語を勉強します」を英語にすると？', 'I study English every day.', '習慣的な動作は現在形を使います。every day, usually, alwaysなどが目印。', 'easy', '{"現在形","頻度副詞"}'),
('時制', 'I ___ (play) tennis when it started to rain.', 'was playing', '過去のある時点で進行中だった動作は過去進行形(was/were + ~ing)を使います。', 'medium', '{"過去進行形","時制の一致"}'),
('時制', 'She ___ already ___ (finish) her homework.', 'has already finished', '「もう〜した」は現在完了形(have/has + 過去分詞)。alreadyはhaveとp.p.の間に入ります。', 'medium', '{"現在完了","完了用法"}'),
('時制', 'I ___ (know) him since 2020.', 'have known', 'sinceは「〜以来ずっと」で現在完了の継続用法と使います。', 'medium', '{"現在完了","継続用法"}'),
('時制', 'If it ___ (rain) tomorrow, I will stay home.', 'rains', '時・条件の副詞節では未来のことでも現在形を使います。if節の中はwillを使いません。', 'hard', '{"条件節","時制の一致"}'),
('時制', '「彼が来るまで待ちます」I will wait ___ he comes.', 'until / till', 'until/till「〜まで」。時の副詞節なのでhe comesと現在形にします。', 'medium', '{"接続詞","時制"}'),
('受動態', 'This book ___ (write) by a famous author.', 'was written', '受動態はbe動詞 + 過去分詞。write-wrote-writtenの変化に注意。', 'easy', '{"受動態","不規則変化"}'),
('受動態', 'English ___ (speak) in many countries.', 'is spoken', '一般的事実の受動態は現在形のbe動詞を使います。speak-spoke-spoken。', 'easy', '{"受動態","現在形"}'),
('受動態', 'The window ___ (break) by the boys yesterday.', 'was broken', '過去の受動態はwas/were + 過去分詞。break-broke-broken。', 'easy', '{"受動態","過去形"}'),
('不定詞・動名詞', 'I enjoy ___ (read) books.', 'reading', 'enjoyは動名詞(~ing)を目的語にとる動詞。to不定詞は使えません。', 'medium', '{"動名詞","enjoy/finish/stop"}'),
('不定詞・動名詞', 'I decided ___ (go) abroad.', 'to go', 'decideはto不定詞を目的語にとる動詞。want, hope, planなども同様。', 'medium', '{"不定詞","decide/want/hope"}'),
('不定詞・動名詞', 'It is important ___ (study) hard.', 'to study', 'It is + 形容詞 + to不定詞：「〜するのは…だ」の形式主語構文。', 'easy', '{"形式主語","It is ~ to"}'),
('不定詞・動名詞', E'I don''t know what ___ (do).', 'to do', '疑問詞 + to不定詞：「何を〜すべきか」。how to, where to, when toなども同様。', 'medium', '{"疑問詞+to不定詞"}'),
('不定詞・動名詞', 'Would you mind ___ (open) the window?', 'opening', 'mindは動名詞を目的語にとります。Would you mind ~ing?「〜していただけますか」', 'medium', '{"動名詞","丁寧な依頼"}'),
('関係代名詞', 'The boy ___ is standing there is my brother. (人)', 'who / that', '先行詞が人の場合、関係代名詞はwho/thatを使います。主格の関係代名詞。', 'medium', '{"who","主格"}'),
('関係代名詞', 'The book ___ I read yesterday was interesting. (物)', 'which / that', '先行詞が物の場合はwhich/that。目的格なので省略も可能。', 'medium', '{"which","目的格"}'),
('関係代名詞', 'I have a friend ___ father is a doctor.', 'whose', 'whoseは所有格の関係代名詞。「〜の」の意味で人にも物にも使えます。', 'hard', '{"whose","所有格"}'),
('比較', 'This bag is ___ (heavy) than that one.', 'heavier', '2つを比べる時はthan + 比較級。heavy → heavier（yをiに変えてer）。', 'easy', '{"比較級","-er"}'),
('比較', 'Mt. Fuji is the ___ (high) mountain in Japan.', 'highest', '3つ以上の中で一番はthe + 最上級。high → highest。', 'easy', '{"最上級","the + -est"}'),
('比較', 'This question is ___ difficult ___ that one. (同じくらい)', 'as ... as', 'as ~ as：「…と同じくらい〜」の原級比較。否定形はnot as ~ as。', 'medium', '{"原級比較","as~as"}'),
('比較', 'English is ___ (useful) than any other language.', 'more useful', '長い形容詞の比較級はmore + 形容詞。useful, important, beautifulなど。', 'medium', '{"比較級","more"}'),
('接続詞', '___ it was raining, we went out. (〜だけど)', 'Although / Though', 'Although/Though「〜だけれども」は譲歩の接続詞。butと一緒には使いません。', 'medium', '{"譲歩","although"}'),
('接続詞', E'I''ll call you ___ I arrive. (〜したら)', 'when / as soon as', 'when/as soon as「〜したら」。時の副詞節では未来のことでも現在形を使います。', 'medium', '{"時の接続詞","現在形"}'),
('接続詞', 'I think ___ he is honest.', 'that', 'thinkの後のthat節。thatは省略可能。I think (that) ~「〜だと思う」。', 'easy', '{"名詞節","that節"}'),
('仮定法', 'If I ___ (be) rich, I would buy a big house.', 'were', '仮定法過去：現在の事実に反する仮定。be動詞は主語に関係なくwereを使います。', 'hard', '{"仮定法過去","If+過去形, would"}'),
('仮定法', 'I wish I ___ (can) fly.', 'could', 'I wish + 仮定法過去：「〜できたらなあ」と現在の実現不可能な願望を表します。', 'hard', '{"I wish","仮定法"}'),
('前置詞', E'I''m interested ___ science.', 'in', 'be interested in ~「〜に興味がある」。前置詞inとセットで覚えましょう。', 'easy', '{"前置詞","形容詞+前置詞"}'),
('前置詞', 'She is good ___ playing the piano.', 'at', 'be good at ~「〜が得意」。前置詞atの後は名詞か動名詞。', 'easy', '{"前置詞","be good at"}'),
('前置詞', E'I''m looking forward ___ seeing you.', 'to', 'look forward to ~ing「〜するのを楽しみにしている」。toの後は動名詞。', 'medium', '{"前置詞","look forward to"}'),
('前置詞', 'The movie was based ___ a true story.', 'on', 'be based on ~「〜に基づいている」。', 'medium', '{"前置詞","be based on"}'),
('分詞', 'The girl ___ (sing) on the stage is my sister.', 'singing', '現在分詞の後置修飾。「ステージで歌っている女の子」名詞を後ろから修飾。', 'medium', '{"現在分詞","後置修飾"}'),
('分詞', 'The language ___ (speak) in Brazil is Portuguese.', 'spoken', '過去分詞の後置修飾。「ブラジルで話されている言語」受動の意味。', 'medium', '{"過去分詞","後置修飾"}'),
('分詞', 'The movie was very ___ (excite).', 'exciting', '物が主語→現在分詞(-ing)「わくわくさせる」。人が主語→過去分詞(-ed)「わくわくした」。', 'medium', '{"分詞形容詞","-ing/-ed"}'),
('助動詞', 'You ___ (〜しなくてよい) come tomorrow.', E'don''t have to', E'don''t have to「〜しなくてよい」（不必要）。must not「〜してはいけない」（禁止）と区別。', 'medium', '{"助動詞","不必要と禁止"}'),
('助動詞', 'You ___ not tell anyone about this. (禁止)', 'must', E'must not「〜してはいけない」は強い禁止。don''t have toと混同しないよう注意。', 'medium', '{"must not","禁止"}'),
('助動詞', '___ you like some coffee? (勧誘)', 'Would', 'Would you like ~?「〜はいかがですか」丁寧な勧誘表現。', 'easy', '{"would","丁寧表現"}'),
('代名詞', 'I lost my pen. Can I borrow ___? (あなたのもの)', 'yours', 'yours = your pen。所有代名詞で名詞の繰り返しを避けます。', 'easy', '{"所有代名詞","mine/yours"}'),
('代名詞', '___ of the students passed the exam. (全員)', 'All', 'all of ~「〜の全員」。each, some, none, mostなどと比較して覚えましょう。', 'easy', '{"数量代名詞","all/each/some"}'),
('文型', 'She made me ___ (happy の位置)', 'She made me happy.', 'SVOC（第5文型）：make + O + C「OをCにする」。Cには形容詞が入ります。', 'medium', '{"第5文型","make+O+C"}'),
('文型', 'My mother let me ___ (go) to the party.', 'go', 'let + O + 原形不定詞「Oに〜させてあげる」。toは不要。', 'hard', '{"使役動詞","let/make/have"}'),
('疑問文', '___ do you think about this plan? (意見を聞く)', 'What', 'What do you think about/of ~?「〜についてどう思いますか」。', 'easy', '{"疑問詞","意見を聞く"}'),
('疑問文', E'You like sushi, ___ you?', E'don''t', '付加疑問文：肯定文の後はdon''t you? 否定文の後はdo you?', 'medium', '{"付加疑問文","確認"}'),
('間接話法', 'He said, "I am tired." → He said that he ___ tired.', 'was', '間接話法では時制が1つ過去にずれます。am → was。', 'hard', '{"間接話法","時制の一致"}'),
('there構文', '___ ___ a lot of people at the party.', 'There were', 'There is/are ~「〜がある/いる」。peopleは複数形なのでwere。', 'easy', '{"there is/are","存在文"}'),
('時制', 'I ___ ___ ___ (wait) for an hour.', 'have been waiting', '現在完了進行形(have been ~ing)：過去から今まで「ずっと〜し続けている」。', 'hard', '{"現在完了進行形"}'),
('構文', 'This box is too heavy ___ (carry).', 'to carry', 'too ~ to …「〜すぎて…できない」。tooの後は形容詞、toの後は原形。', 'medium', '{"too~to","不定詞"}'),
('構文', 'She is old ___ to drive.', 'enough', '形容詞 + enough + to不定詞「〜するのに十分…だ」。enoughは形容詞の後に置きます。', 'medium', '{"enough to","不定詞"}'),
('構文', 'It was ___ a beautiful day that we went to the park.', 'such', 'such + a/an + 形容詞 + 名詞 + that ~「とても…なので〜」。soは形容詞の前に直接。', 'hard', '{"so~that","such~that"}'),
('構文', 'She sat on the bench ___ her eyes closed.', 'with', 'with + O + 過去分詞「Oを〜した状態で」付帯状況のwith。', 'hard', '{"付帯状況","with+O+p.p."}'),
('感嘆文', '___ beautiful this flower is!', 'How', 'How + 形容詞/副詞 + S + V!「なんと〜なんでしょう」。What + a/an + 形容詞 + 名詞と区別。', 'medium', '{"感嘆文","How/What"}'),
('時制', 'By the time he arrived, she ___ already ___ (leave).', 'had already left', '過去完了(had + p.p.)：過去のある時点よりさらに前の出来事を表します。', 'hard', '{"過去完了","大過去"}'),
('関係代名詞', 'This is the town ___ I was born. (場所)', 'where', '関係副詞where：先行詞が場所の時に使います。in whichに書き換え可能。', 'hard', '{"関係副詞","where"}'),
('関係代名詞', 'I remember the day ___ we first met. (時)', 'when', '関係副詞when：先行詞がthe day/time/yearなど時の時に使います。', 'hard', '{"関係副詞","when"}'),
('関係代名詞', 'Tell me the reason ___ you were late.', 'why', '関係副詞why：先行詞がthe reasonの時に使います。for whichに書き換え可能。', 'hard', '{"関係副詞","why"}'),
('不定詞・動名詞', 'He stopped ___ (smoke) last year.', 'smoking', 'stop ~ing「〜するのをやめる」。stop to ~「〜するために立ち止まる」と区別。', 'hard', '{"動名詞","stop ~ing"}');

-- ==============================
-- 語彙 (100件) - 最初の20件のみ記載、残りは同様のパターンで追加
-- ==============================
INSERT INTO vocab_items (word, meaning, example_sentence, type, level, distractors) VALUES
('absolutely', '完全に、絶対に', 'I absolutely agree with your idea.', 'word', '2級', '{"たぶん","ほとんど","だいたい"}'),
('achieve', '達成する', 'She achieved her goal of passing the exam.', 'word', '2級', '{"避ける","認める","許可する"}'),
('atmosphere', '雰囲気、大気', 'The restaurant has a wonderful atmosphere.', 'word', '2級', '{"温度","天気","環境"}'),
('available', '利用できる、入手可能な', 'Is this seat available?', 'word', '2級', '{"避けられない","受け入れられる","信頼できる"}'),
('behavior', '行動、ふるまい', 'His behavior was very polite.', 'word', '2級', '{"信念","利益","能力"}'),
('benefit', '利益、恩恵', 'Exercise has many health benefits.', 'word', '2級', '{"負担","障害","罰"}'),
('challenge', '挑戦、課題', 'Learning a new language is a big challenge.', 'word', '2級', '{"機会","変化","選択"}'),
('citizen', '市民', 'Every citizen has the right to vote.', 'word', '2級', '{"顧客","選手","患者"}'),
('complicated', '複雑な', 'The instructions were too complicated.', 'word', '2級', '{"簡単な","退屈な","危険な"}'),
('concerned', '心配している、関係のある', E'I''m concerned about your health.', 'word', '2級', '{"確信している","満足している","驚いている"}'),
('confidence', '自信', 'She spoke with great confidence.', 'word', '2級', '{"混乱","競争","注意"}'),
('consequence', '結果、影響', 'You must accept the consequences of your actions.', 'word', '2級', '{"原因","証拠","会議"}'),
('contribute', '貢献する、寄付する', 'She contributed a lot to the project.', 'word', '2級', '{"矛盾する","管理する","比較する"}'),
('convince', '説得する、納得させる', 'He convinced me to join the team.', 'word', '2級', '{"混乱させる","招待する","批判する"}'),
('decrease', '減少する', 'The number of students has decreased.', 'word', '2級', '{"増加する","維持する","発見する"}'),
('demonstrate', '実演する、証明する', 'The teacher demonstrated how to use the tool.', 'word', '2級', '{"破壊する","装飾する","拒否する"}'),
('depend', '〜による、頼る', 'It depends on the weather.', 'word', '2級', '{"延期する","守る","否定する"}'),
('determine', '決定する、決心する', 'We need to determine the cause of the problem.', 'word', '2級', '{"検出する","遅延する","配達する"}'),
('develop', '発展させる、開発する', 'The company developed a new product.', 'word', '2級', '{"削除する","配達する","拒否する"}'),
('distinguish', '区別する', 'Can you distinguish between the two colors?', 'word', '2級', '{"分配する","消滅する","混乱させる"}'),
('as a result', 'その結果', E'He didn''t study. As a result, he failed the exam.', 'idiom', '2級', '{"一方で","例えば","ところで"}'),
('in addition', 'さらに、加えて', 'In addition, we need to consider the budget.', 'idiom', '2級', '{"代わりに","その結果","つまり"}'),
('on the other hand', '一方で', E'It''s expensive. On the other hand, it''s very durable.', 'idiom', '2級', '{"その結果","さらに","例えば"}'),
('take advantage of', '〜を利用する', 'We should take advantage of this opportunity.', 'phrase', '2級', '{"〜の世話をする","〜に注意する","〜を諦める"}'),
('come up with', '〜を思いつく', 'She came up with a great idea.', 'phrase', '2級', '{"〜に追いつく","〜を我慢する","〜を調べる"}'),
('look into', '〜を調べる', E'I''ll look into the matter right away.', 'phrase', '2級', '{"〜を見つける","〜を探す","〜を見守る"}'),
('put off', '延期する', 'We had to put off the meeting.', 'phrase', '2級', '{"取り消す","続ける","準備する"}'),
('turn out', '結局〜だとわかる', 'It turned out that he was right.', 'phrase', '2級', '{"消す","回す","始まる"}'),
('carry out', '実行する', 'We need to carry out the plan carefully.', 'phrase', '2級', '{"運び出す","持ち帰る","配る"}'),
('make up for', '〜を埋め合わせる', E'I''ll make up for lost time.', 'phrase', '2級', '{"〜をでっち上げる","〜を化粧する","〜を構成する"}');
