// のびしろクエスト — シードデータ
import type {
  User,
  Subject,
  Question,
  Badge,
  Reward,
  CharacterLine,
} from './types';

// ---------------------------------------------------------------------------
// 1. USERS
// ---------------------------------------------------------------------------
export const USERS: User[] = [
  {
    id: 'mitsuki',
    name: 'みつき',
    grade: '新中学3年生',
    goal: '都立高校合格',
    theme: 'junior',
    subjects: ['数学', '英語', '国語', '理科', '社会'],
  },
  {
    id: 'michiru',
    name: 'みちる',
    grade: '新小学6年生',
    goal: '大妻中学合格',
    theme: 'elementary',
    subjects: ['算数', '国語', '理科', '社会'],
  },
];

// ---------------------------------------------------------------------------
// 2. SUBJECTS (with units)
// ---------------------------------------------------------------------------
export const SUBJECTS: Subject[] = [
  // ===== みつき — 数学 =====
  {
    id: 'mitsuki-math',
    name: '数学',
    userType: 'mitsuki',
    units: [
      { id: 'mitsuki-math-01', subjectId: 'mitsuki-math', name: '正負の数', order: 1 },
      { id: 'mitsuki-math-02', subjectId: 'mitsuki-math', name: '文字式', order: 2 },
      { id: 'mitsuki-math-03', subjectId: 'mitsuki-math', name: '一次方程式', order: 3 },
      { id: 'mitsuki-math-04', subjectId: 'mitsuki-math', name: '連立方程式', order: 4 },
      { id: 'mitsuki-math-05', subjectId: 'mitsuki-math', name: '一次関数', order: 5 },
      { id: 'mitsuki-math-06', subjectId: 'mitsuki-math', name: '図形', order: 6 },
      { id: 'mitsuki-math-07', subjectId: 'mitsuki-math', name: '確率', order: 7 },
      { id: 'mitsuki-math-08', subjectId: 'mitsuki-math', name: '資料の活用', order: 8 },
    ],
  },
  // ===== みつき — 英語 =====
  {
    id: 'mitsuki-english',
    name: '英語',
    userType: 'mitsuki',
    units: [
      { id: 'mitsuki-eng-01', subjectId: 'mitsuki-english', name: 'be動詞', order: 1 },
      { id: 'mitsuki-eng-02', subjectId: 'mitsuki-english', name: '一般動詞', order: 2 },
      { id: 'mitsuki-eng-03', subjectId: 'mitsuki-english', name: '助動詞', order: 3 },
      { id: 'mitsuki-eng-04', subjectId: 'mitsuki-english', name: '過去形', order: 4 },
      { id: 'mitsuki-eng-05', subjectId: 'mitsuki-english', name: '進行形', order: 5 },
      { id: 'mitsuki-eng-06', subjectId: 'mitsuki-english', name: '不定詞', order: 6 },
      { id: 'mitsuki-eng-07', subjectId: 'mitsuki-english', name: '動名詞', order: 7 },
      { id: 'mitsuki-eng-08', subjectId: 'mitsuki-english', name: '比較', order: 8 },
      { id: 'mitsuki-eng-09', subjectId: 'mitsuki-english', name: '基本文法', order: 9 },
      { id: 'mitsuki-eng-10', subjectId: 'mitsuki-english', name: '単語', order: 10 },
    ],
  },
  // ===== みつき — 国語 =====
  {
    id: 'mitsuki-japanese',
    name: '国語',
    userType: 'mitsuki',
    units: [
      { id: 'mitsuki-jpn-01', subjectId: 'mitsuki-japanese', name: '漢字', order: 1 },
      { id: 'mitsuki-jpn-02', subjectId: 'mitsuki-japanese', name: '文法', order: 2 },
      { id: 'mitsuki-jpn-03', subjectId: 'mitsuki-japanese', name: '説明文', order: 3 },
      { id: 'mitsuki-jpn-04', subjectId: 'mitsuki-japanese', name: '物語文', order: 4 },
      { id: 'mitsuki-jpn-05', subjectId: 'mitsuki-japanese', name: '古文の基礎', order: 5 },
    ],
  },
  // ===== みつき — 理科 =====
  {
    id: 'mitsuki-science',
    name: '理科',
    userType: 'mitsuki',
    units: [
      { id: 'mitsuki-sci-01', subjectId: 'mitsuki-science', name: '物質', order: 1 },
      { id: 'mitsuki-sci-02', subjectId: 'mitsuki-science', name: '化学変化', order: 2 },
      { id: 'mitsuki-sci-03', subjectId: 'mitsuki-science', name: '電流', order: 3 },
      { id: 'mitsuki-sci-04', subjectId: 'mitsuki-science', name: '光・音', order: 4 },
      { id: 'mitsuki-sci-05', subjectId: 'mitsuki-science', name: '生物', order: 5 },
      { id: 'mitsuki-sci-06', subjectId: 'mitsuki-science', name: '地学の基礎', order: 6 },
    ],
  },
  // ===== みつき — 社会 =====
  {
    id: 'mitsuki-social',
    name: '社会',
    userType: 'mitsuki',
    units: [
      { id: 'mitsuki-soc-01', subjectId: 'mitsuki-social', name: '地理', order: 1 },
      { id: 'mitsuki-soc-02', subjectId: 'mitsuki-social', name: '歴史', order: 2 },
      { id: 'mitsuki-soc-03', subjectId: 'mitsuki-social', name: '公民の入口', order: 3 },
    ],
  },

  // ===== みちる — 算数 =====
  {
    id: 'michiru-math',
    name: '算数',
    userType: 'michiru',
    units: [
      { id: 'michiru-math-01', subjectId: 'michiru-math', name: '小数', order: 1 },
      { id: 'michiru-math-02', subjectId: 'michiru-math', name: '分数', order: 2 },
      { id: 'michiru-math-03', subjectId: 'michiru-math', name: '割合', order: 3 },
      { id: 'michiru-math-04', subjectId: 'michiru-math', name: '速さ', order: 4 },
      { id: 'michiru-math-05', subjectId: 'michiru-math', name: '面積', order: 5 },
      { id: 'michiru-math-06', subjectId: 'michiru-math', name: '体積', order: 6 },
      { id: 'michiru-math-07', subjectId: 'michiru-math', name: '図形', order: 7 },
      { id: 'michiru-math-08', subjectId: 'michiru-math', name: '規則性', order: 8 },
      { id: 'michiru-math-09', subjectId: 'michiru-math', name: '場合の数の基礎', order: 9 },
    ],
  },
  // ===== みちる — 国語 =====
  {
    id: 'michiru-japanese',
    name: '国語',
    userType: 'michiru',
    units: [
      { id: 'michiru-jpn-01', subjectId: 'michiru-japanese', name: '漢字', order: 1 },
      { id: 'michiru-jpn-02', subjectId: 'michiru-japanese', name: '語彙', order: 2 },
      { id: 'michiru-jpn-03', subjectId: 'michiru-japanese', name: 'ことわざ', order: 3 },
      { id: 'michiru-jpn-04', subjectId: 'michiru-japanese', name: '慣用句', order: 4 },
      { id: 'michiru-jpn-05', subjectId: 'michiru-japanese', name: '説明文', order: 5 },
      { id: 'michiru-jpn-06', subjectId: 'michiru-japanese', name: '物語文', order: 6 },
      { id: 'michiru-jpn-07', subjectId: 'michiru-japanese', name: '主語述語', order: 7 },
      { id: 'michiru-jpn-08', subjectId: 'michiru-japanese', name: '接続語', order: 8 },
      { id: 'michiru-jpn-09', subjectId: 'michiru-japanese', name: '要旨', order: 9 },
    ],
  },
  // ===== みちる — 理科 =====
  {
    id: 'michiru-science',
    name: '理科',
    userType: 'michiru',
    units: [
      { id: 'michiru-sci-01', subjectId: 'michiru-science', name: '植物', order: 1 },
      { id: 'michiru-sci-02', subjectId: 'michiru-science', name: '動物', order: 2 },
      { id: 'michiru-sci-03', subjectId: 'michiru-science', name: '天気', order: 3 },
      { id: 'michiru-sci-04', subjectId: 'michiru-science', name: '水の変化', order: 4 },
      { id: 'michiru-sci-05', subjectId: 'michiru-science', name: 'てこ', order: 5 },
      { id: 'michiru-sci-06', subjectId: 'michiru-science', name: '電気', order: 6 },
      { id: 'michiru-sci-07', subjectId: 'michiru-science', name: '月と星', order: 7 },
    ],
  },
  // ===== みちる — 社会 =====
  {
    id: 'michiru-social',
    name: '社会',
    userType: 'michiru',
    units: [
      { id: 'michiru-soc-01', subjectId: 'michiru-social', name: '日本の地理', order: 1 },
      { id: 'michiru-soc-02', subjectId: 'michiru-social', name: '都道府県', order: 2 },
      { id: 'michiru-soc-03', subjectId: 'michiru-social', name: '産業', order: 3 },
      { id: 'michiru-soc-04', subjectId: 'michiru-social', name: '歴史人物基礎', order: 4 },
      { id: 'michiru-soc-05', subjectId: 'michiru-social', name: '日本のくらし', order: 5 },
      { id: 'michiru-soc-06', subjectId: 'michiru-social', name: '政治の入口', order: 6 },
    ],
  },
];

// ---------------------------------------------------------------------------
// 3. QUESTIONS
// ---------------------------------------------------------------------------
export const QUESTIONS: Question[] = [
  // ======================== みつき — 数学 (10) ========================
  {
    id: 'mq-001',
    userType: 'mitsuki',
    subject: '数学',
    unit: '正負の数',
    format: 'multiple_choice',
    question: '(-3) + (+7) の答えは？',
    choices: ['-10', '-4', '4', '10'],
    answer: '4',
    explanation: '異符号の加法では絶対値の大きい方の符号をとり、絶対値の差を求めます。7 - 3 = 4',
    difficulty: 'easy',
    tags: ['正負の数', '加法'],
  },
  {
    id: 'mq-002',
    userType: 'mitsuki',
    subject: '数学',
    unit: '正負の数',
    format: 'true_false',
    question: '(-5) × (-2) = -10 である。',
    answer: '×',
    explanation: '負×負=正なので (-5) × (-2) = +10 です。',
    difficulty: 'easy',
    tags: ['正負の数', '乗法'],
  },
  {
    id: 'mq-003',
    userType: 'mitsuki',
    subject: '数学',
    unit: '文字式',
    format: 'fill_blank',
    question: '3a + 2a を簡単にすると？',
    answer: '5a',
    explanation: '同類項をまとめます。3a + 2a = (3+2)a = 5a',
    difficulty: 'easy',
    tags: ['文字式', '同類項'],
  },
  {
    id: 'mq-004',
    userType: 'mitsuki',
    subject: '数学',
    unit: '一次方程式',
    format: 'fill_blank',
    question: '2x + 3 = 11 のとき、x の値は？',
    answer: '4',
    explanation: '2x = 11 - 3 = 8、x = 8 ÷ 2 = 4',
    difficulty: 'easy',
    tags: ['一次方程式'],
  },
  {
    id: 'mq-005',
    userType: 'mitsuki',
    subject: '数学',
    unit: '連立方程式',
    format: 'multiple_choice',
    question: 'x + y = 5、x - y = 1 のとき、x の値は？',
    choices: ['2', '3', '4', '5'],
    answer: '3',
    explanation: '2式を足すと 2x = 6、x = 3。y = 5 - 3 = 2',
    difficulty: 'normal',
    tags: ['連立方程式', '加減法'],
  },
  {
    id: 'mq-006',
    userType: 'mitsuki',
    subject: '数学',
    unit: '一次関数',
    format: 'fill_blank',
    question: 'y = 2x + 1 のグラフの傾きは？',
    answer: '2',
    explanation: 'y = ax + b の形で、a が傾きです。この場合 a = 2。',
    difficulty: 'easy',
    tags: ['一次関数', '傾き'],
  },
  {
    id: 'mq-007',
    userType: 'mitsuki',
    subject: '数学',
    unit: '図形',
    format: 'multiple_choice',
    question: '三角形の内角の和は何度？',
    choices: ['90度', '180度', '270度', '360度'],
    answer: '180度',
    explanation: '三角形の内角の和は必ず180度です。',
    difficulty: 'easy',
    tags: ['図形', '角度'],
  },
  {
    id: 'mq-008',
    userType: 'mitsuki',
    subject: '数学',
    unit: '確率',
    format: 'multiple_choice',
    question: 'サイコロを1回振って偶数が出る確率は？',
    choices: ['1/6', '1/3', '1/2', '2/3'],
    answer: '1/2',
    explanation: '偶数は2,4,6の3通り。全体は6通り。3/6 = 1/2。',
    difficulty: 'easy',
    tags: ['確率'],
  },
  {
    id: 'mq-009',
    userType: 'mitsuki',
    subject: '数学',
    unit: '一次方程式',
    format: 'multiple_choice',
    question: '3(x - 2) = 12 のとき x は？',
    choices: ['2', '4', '6', '8'],
    answer: '6',
    explanation: 'x - 2 = 4、x = 6',
    difficulty: 'normal',
    tags: ['一次方程式', '分配法則'],
  },
  {
    id: 'mq-010',
    userType: 'mitsuki',
    subject: '数学',
    unit: '資料の活用',
    format: 'true_false',
    question: '中央値とは、データを小さい順に並べたときのちょうど真ん中の値のことである。',
    answer: '○',
    explanation: 'データを値の大きさ順に並べたとき、真ん中にくる値が中央値（メジアン）です。',
    difficulty: 'easy',
    tags: ['資料の活用', '中央値'],
  },

  // ======================== みつき — 英語 (10) ========================
  {
    id: 'me-001',
    userType: 'mitsuki',
    subject: '英語',
    unit: 'be動詞',
    format: 'multiple_choice',
    question: '"She ___ a student." 空欄に入るbe動詞は？',
    choices: ['am', 'is', 'are', 'be'],
    answer: 'is',
    explanation: '三人称単数（She）にはisを使います。',
    difficulty: 'easy',
    tags: ['be動詞', '主語と動詞の一致'],
  },
  {
    id: 'me-002',
    userType: 'mitsuki',
    subject: '英語',
    unit: '一般動詞',
    format: 'fill_blank',
    question: '"He ___ soccer every day." (play を正しい形に)',
    answer: 'plays',
    explanation: '三人称単数現在なので -s をつけて plays。',
    difficulty: 'easy',
    tags: ['一般動詞', '三単現のs'],
  },
  {
    id: 'me-003',
    userType: 'mitsuki',
    subject: '英語',
    unit: '助動詞',
    format: 'multiple_choice',
    question: '"You ___ go now." 「行ってもいいよ」と許可する場合、空欄に入るのは？',
    choices: ['must', 'may', 'shall', 'would'],
    answer: 'may',
    explanation: 'may は「～してもよい」という許可を表します。',
    difficulty: 'normal',
    tags: ['助動詞', 'may'],
  },
  {
    id: 'me-004',
    userType: 'mitsuki',
    subject: '英語',
    unit: '過去形',
    format: 'fill_blank',
    question: '"I ___ to the park yesterday." (go の過去形)',
    answer: 'went',
    explanation: 'go は不規則動詞で、過去形は went です。',
    difficulty: 'easy',
    tags: ['過去形', '不規則動詞'],
  },
  {
    id: 'me-005',
    userType: 'mitsuki',
    subject: '英語',
    unit: '進行形',
    format: 'true_false',
    question: '"I am playing tennis now." は現在進行形の正しい文である。',
    answer: '○',
    explanation: 'am/is/are + 動詞ing で現在進行形を作ります。',
    difficulty: 'easy',
    tags: ['進行形', '現在進行形'],
  },
  {
    id: 'me-006',
    userType: 'mitsuki',
    subject: '英語',
    unit: '不定詞',
    format: 'multiple_choice',
    question: '"I want ___ a new book." 空欄に入るのは？',
    choices: ['buy', 'to buy', 'buying', 'bought'],
    answer: 'to buy',
    explanation: 'want の後は to 不定詞（to + 動詞の原形）を使います。',
    difficulty: 'easy',
    tags: ['不定詞', '名詞的用法'],
  },
  {
    id: 'me-007',
    userType: 'mitsuki',
    subject: '英語',
    unit: '動名詞',
    format: 'multiple_choice',
    question: '"I enjoy ___ music." 空欄に入るのは？',
    choices: ['listen', 'to listen', 'listening', 'listened'],
    answer: 'listening',
    explanation: 'enjoy の後は動名詞（～ing）を使います。',
    difficulty: 'normal',
    tags: ['動名詞'],
  },
  {
    id: 'me-008',
    userType: 'mitsuki',
    subject: '英語',
    unit: '比較',
    format: 'fill_blank',
    question: '"Mt. Fuji is the ___ mountain in Japan." (high の最上級)',
    answer: 'highest',
    explanation: 'the + 最上級で「最も～」を表します。high → highest。',
    difficulty: 'normal',
    tags: ['比較', '最上級'],
  },
  {
    id: 'me-009',
    userType: 'mitsuki',
    subject: '英語',
    unit: '基本文法',
    format: 'multiple_choice',
    question: '"There ___ two cats in the room." 空欄に入るのは？',
    choices: ['is', 'are', 'am', 'be'],
    answer: 'are',
    explanation: 'There is/are構文では後ろの名詞に合わせます。two cats は複数なので are。',
    difficulty: 'easy',
    tags: ['基本文法', 'There is/are'],
  },
  {
    id: 'me-010',
    userType: 'mitsuki',
    subject: '英語',
    unit: '単語',
    format: 'multiple_choice',
    question: '"library" の意味は？',
    choices: ['書店', '図書館', '教室', '病院'],
    answer: '図書館',
    explanation: 'library = 図書館。bookstore が書店です。',
    difficulty: 'easy',
    tags: ['単語', '名詞'],
  },

  // ======================== みつき — 国語 (10) ========================
  {
    id: 'mj-001',
    userType: 'mitsuki',
    subject: '国語',
    unit: '漢字',
    format: 'fill_blank',
    question: '「困難にたちむ（　）う」のカッコに入る漢字は？',
    answer: '向',
    explanation: '「立ち向かう」＝困難に立ち向かう。',
    difficulty: 'easy',
    tags: ['漢字', '書き取り'],
  },
  {
    id: 'mj-002',
    userType: 'mitsuki',
    subject: '国語',
    unit: '漢字',
    format: 'multiple_choice',
    question: '「沿革」の読みは？',
    choices: ['えんかく', 'えんげき', 'そうかく', 'せんかく'],
    answer: 'えんかく',
    explanation: '沿革（えんかく）＝物事の移り変わりの歴史。',
    difficulty: 'normal',
    tags: ['漢字', '読み'],
  },
  {
    id: 'mj-003',
    userType: 'mitsuki',
    subject: '国語',
    unit: '文法',
    format: 'multiple_choice',
    question: '「美しい」の品詞は？',
    choices: ['名詞', '動詞', '形容詞', '副詞'],
    answer: '形容詞',
    explanation: '「美しい」は「い」で終わる形容詞です。',
    difficulty: 'easy',
    tags: ['文法', '品詞'],
  },
  {
    id: 'mj-004',
    userType: 'mitsuki',
    subject: '国語',
    unit: '文法',
    format: 'true_false',
    question: '「走る」は五段活用の動詞である。',
    answer: '○',
    explanation: '「走らない・走ります・走る・走れば・走ろう」と五段に活用します。',
    difficulty: 'normal',
    tags: ['文法', '動詞の活用'],
  },
  {
    id: 'mj-005',
    userType: 'mitsuki',
    subject: '国語',
    unit: '説明文',
    format: 'multiple_choice',
    question: '説明文で「つまり」という接続語が果たす役割は？',
    choices: ['逆接', '並列', '要約・言い換え', '例示'],
    answer: '要約・言い換え',
    explanation: '「つまり」は前の内容をまとめたり言い換えたりする接続語です。',
    difficulty: 'easy',
    tags: ['説明文', '接続語'],
  },
  {
    id: 'mj-006',
    userType: 'mitsuki',
    subject: '国語',
    unit: '物語文',
    format: 'multiple_choice',
    question: '物語文で登場人物の心情を読み取る手がかりとして最も適切なものは？',
    choices: ['段落の数', '漢字の量', '行動・会話・情景描写', 'ページ数'],
    answer: '行動・会話・情景描写',
    explanation: '心情は直接書かれないことが多く、行動・会話・情景描写から読み取ります。',
    difficulty: 'normal',
    tags: ['物語文', '心情理解'],
  },
  {
    id: 'mj-007',
    userType: 'mitsuki',
    subject: '国語',
    unit: '古文の基礎',
    format: 'fill_blank',
    question: '古文の「いとをかし」を現代語に訳すと「とても（　）」。',
    answer: '趣がある',
    explanation: '「いと」=とても、「をかし」=趣がある・面白い。',
    difficulty: 'normal',
    tags: ['古文', '現代語訳'],
  },
  {
    id: 'mj-008',
    userType: 'mitsuki',
    subject: '国語',
    unit: '古文の基礎',
    format: 'multiple_choice',
    question: '『枕草子』の作者は？',
    choices: ['紫式部', '清少納言', '和泉式部', '赤染衛門'],
    answer: '清少納言',
    explanation: '枕草子は清少納言の随筆です。紫式部は源氏物語の作者。',
    difficulty: 'easy',
    tags: ['古文', '文学史'],
  },
  {
    id: 'mj-009',
    userType: 'mitsuki',
    subject: '国語',
    unit: '漢字',
    format: 'fill_blank',
    question: '「はんえい」を漢字で書くと？',
    answer: '繁栄',
    explanation: '繁栄（はんえい）＝栄えて盛んなこと。',
    difficulty: 'normal',
    tags: ['漢字', '書き取り'],
  },
  {
    id: 'mj-010',
    userType: 'mitsuki',
    subject: '国語',
    unit: '文法',
    format: 'multiple_choice',
    question: '「静かだ」の品詞は？',
    choices: ['形容詞', '形容動詞', '副詞', '動詞'],
    answer: '形容動詞',
    explanation: '「だ」で終わる活用語で、物事の性質や状態を表すのが形容動詞です。',
    difficulty: 'normal',
    tags: ['文法', '品詞'],
  },

  // ======================== みちる — 算数 (10) ========================
  {
    id: 'cq-001',
    userType: 'michiru',
    subject: '算数',
    unit: '分数',
    format: 'multiple_choice',
    question: '1/3 + 1/6 はいくつ？',
    choices: ['1/9', '2/9', '1/2', '2/6'],
    answer: '1/2',
    explanation: '通分すると 2/6 + 1/6 = 3/6 = 1/2 です。',
    difficulty: 'easy',
    tags: ['分数', '通分', '加法'],
  },
  {
    id: 'cq-002',
    userType: 'michiru',
    subject: '算数',
    unit: '割合',
    format: 'fill_blank',
    question: '200円の30%はいくら？',
    answer: '60',
    explanation: '200 × 0.3 = 60（円）',
    difficulty: 'easy',
    tags: ['割合', '百分率'],
  },
  {
    id: 'cq-003',
    userType: 'michiru',
    subject: '算数',
    unit: '速さ',
    format: 'multiple_choice',
    question: '時速60kmで2時間走ると何km進む？',
    choices: ['30km', '60km', '120km', '180km'],
    answer: '120km',
    explanation: '距離＝速さ×時間＝60×2＝120km',
    difficulty: 'easy',
    tags: ['速さ', '距離'],
  },
  {
    id: 'cq-004',
    userType: 'michiru',
    subject: '算数',
    unit: '面積',
    format: 'fill_blank',
    question: '底辺8cm、高さ5cmの三角形の面積は？（単位はcm²）',
    answer: '20',
    explanation: '三角形の面積＝底辺×高さ÷2＝8×5÷2＝20cm²',
    difficulty: 'easy',
    tags: ['面積', '三角形'],
  },
  {
    id: 'cq-005',
    userType: 'michiru',
    subject: '算数',
    unit: '小数',
    format: 'multiple_choice',
    question: '0.25 × 4 はいくつ？',
    choices: ['0.5', '1', '1.25', '0.1'],
    answer: '1',
    explanation: '0.25 × 4 = 1.00 = 1',
    difficulty: 'easy',
    tags: ['小数', '乗法'],
  },
  {
    id: 'cq-006',
    userType: 'michiru',
    subject: '算数',
    unit: '体積',
    format: 'fill_blank',
    question: '縦3cm、横4cm、高さ5cmの直方体の体積は？（単位はcm³）',
    answer: '60',
    explanation: '体積＝縦×横×高さ＝3×4×5＝60cm³',
    difficulty: 'easy',
    tags: ['体積', '直方体'],
  },
  {
    id: 'cq-007',
    userType: 'michiru',
    subject: '算数',
    unit: '図形',
    format: 'true_false',
    question: '正方形はすべての辺の長さが等しい。',
    answer: '○',
    explanation: '正方形は4つの辺がすべて等しく、4つの角がすべて直角の四角形です。',
    difficulty: 'easy',
    tags: ['図形', '正方形'],
  },
  {
    id: 'cq-008',
    userType: 'michiru',
    subject: '算数',
    unit: '規則性',
    format: 'fill_blank',
    question: '2, 5, 8, 11, ？ — ？に入る数は？',
    answer: '14',
    explanation: '3ずつ増える等差数列です。11 + 3 = 14。',
    difficulty: 'easy',
    tags: ['規則性', '等差数列'],
  },
  {
    id: 'cq-009',
    userType: 'michiru',
    subject: '算数',
    unit: '場合の数の基礎',
    format: 'multiple_choice',
    question: '赤・青・黄の3色から2色を選ぶ組み合わせは何通り？',
    choices: ['2通り', '3通り', '4通り', '6通り'],
    answer: '3通り',
    explanation: '(赤,青)(赤,黄)(青,黄) の3通りです。',
    difficulty: 'normal',
    tags: ['場合の数', '組み合わせ'],
  },
  {
    id: 'cq-010',
    userType: 'michiru',
    subject: '算数',
    unit: '割合',
    format: 'multiple_choice',
    question: '定価500円の品物が2割引き。売値はいくら？',
    choices: ['300円', '350円', '400円', '450円'],
    answer: '400円',
    explanation: '2割引き＝20%引き。500 × 0.8 = 400円。',
    difficulty: 'normal',
    tags: ['割合', '割引'],
  },

  // ======================== みちる — 国語 (10) ========================
  {
    id: 'cj-001',
    userType: 'michiru',
    subject: '国語',
    unit: '漢字',
    format: 'fill_blank',
    question: '「いっしょうけんめい」を漢字で書くと？',
    answer: '一生懸命',
    explanation: '一生懸命（いっしょうけんめい）＝全力で取り組むこと。',
    difficulty: 'easy',
    tags: ['漢字', '書き取り'],
  },
  {
    id: 'cj-002',
    userType: 'michiru',
    subject: '国語',
    unit: 'ことわざ',
    format: 'multiple_choice',
    question: '「猿も木から（　）」のカッコに入るのは？',
    choices: ['降りる', '落ちる', '飛ぶ', '登る'],
    answer: '落ちる',
    explanation: '「猿も木から落ちる」＝上手な人でも失敗することがある。',
    difficulty: 'easy',
    tags: ['ことわざ'],
  },
  {
    id: 'cj-003',
    userType: 'michiru',
    subject: '国語',
    unit: '慣用句',
    format: 'multiple_choice',
    question: '「頭をひねる」の意味は？',
    choices: ['怒る', 'よく考える', 'あきれる', '眠くなる'],
    answer: 'よく考える',
    explanation: '「頭をひねる」＝よく考える、工夫するという意味の慣用句です。',
    difficulty: 'easy',
    tags: ['慣用句'],
  },
  {
    id: 'cj-004',
    userType: 'michiru',
    subject: '国語',
    unit: '主語述語',
    format: 'fill_blank',
    question: '「花が美しく咲いた。」の主語は？',
    answer: '花が',
    explanation: '「何が」にあたる部分が主語です。「花が」が主語、「咲いた」が述語。',
    difficulty: 'easy',
    tags: ['主語述語'],
  },
  {
    id: 'cj-005',
    userType: 'michiru',
    subject: '国語',
    unit: '接続語',
    format: 'multiple_choice',
    question: '「雨が降った。（　）遠足は中止になった。」最も適切な接続語は？',
    choices: ['しかし', 'だから', 'また', 'つまり'],
    answer: 'だから',
    explanation: '原因→結果の関係なので「だから」（順接）が適切です。',
    difficulty: 'easy',
    tags: ['接続語', '順接'],
  },
  {
    id: 'cj-006',
    userType: 'michiru',
    subject: '国語',
    unit: '語彙',
    format: 'multiple_choice',
    question: '「おだやか」の対義語は？',
    choices: ['にぎやか', 'はげしい', 'おとなしい', 'さわやか'],
    answer: 'はげしい',
    explanation: '「おだやか（穏やか）」の反対は「はげしい（激しい）」です。',
    difficulty: 'easy',
    tags: ['語彙', '対義語'],
  },
  {
    id: 'cj-007',
    userType: 'michiru',
    subject: '国語',
    unit: '説明文',
    format: 'true_false',
    question: '説明文の「要旨」とは、筆者が最も伝えたい中心的な考えのことである。',
    answer: '○',
    explanation: '要旨＝文章全体を通して筆者が最も伝えたい中心的な考え（主張）です。',
    difficulty: 'easy',
    tags: ['説明文', '要旨'],
  },
  {
    id: 'cj-008',
    userType: 'michiru',
    subject: '国語',
    unit: '漢字',
    format: 'multiple_choice',
    question: '「快晴」の「快」の読みは？',
    choices: ['かい', 'こう', 'がい', 'けい'],
    answer: 'かい',
    explanation: '快晴（かいせい）＝雲がほとんどない晴天のこと。',
    difficulty: 'easy',
    tags: ['漢字', '読み'],
  },
  {
    id: 'cj-009',
    userType: 'michiru',
    subject: '国語',
    unit: '物語文',
    format: 'multiple_choice',
    question: '物語文で「情景描写」が表しているものは？',
    choices: ['登場人物の年齢', '場面の様子や雰囲気', '作者の経歴', '文章の長さ'],
    answer: '場面の様子や雰囲気',
    explanation: '情景描写は場面の風景や雰囲気を描き、登場人物の心情を暗示することもあります。',
    difficulty: 'normal',
    tags: ['物語文', '情景描写'],
  },
  {
    id: 'cj-010',
    userType: 'michiru',
    subject: '国語',
    unit: '要旨',
    format: 'multiple_choice',
    question: '文章の要旨をまとめるとき、最も大切なのは？',
    choices: ['細かいデータをすべて書く', '自分の感想を書く', '筆者の主張を短くまとめる', '登場人物を列挙する'],
    answer: '筆者の主張を短くまとめる',
    explanation: '要旨は筆者の中心的な主張を簡潔にまとめたものです。',
    difficulty: 'normal',
    tags: ['要旨', '読解'],
  },
];

// ---------------------------------------------------------------------------
// 4. BADGES
// ---------------------------------------------------------------------------
export const BADGES: Badge[] = [
  // — Streak —
  { id: 'streak-1', name: 'はじめの一歩', icon: '👣', category: 'streak', description: '初めて1日学習した', condition: 'streak', threshold: 1 },
  { id: 'streak-3', name: '3日連続', icon: '🔥', category: 'streak', description: '3日連続で学習した', condition: 'streak', threshold: 3 },
  { id: 'streak-7', name: '7日連続', icon: '🌟', category: 'streak', description: '7日連続で学習した', condition: 'streak', threshold: 7 },
  { id: 'streak-10', name: '春休み前半クリア', icon: '🌸', category: 'streak', description: '10日連続で学習した', condition: 'streak', threshold: 10 },
  { id: 'streak-20', name: '春休み完走', icon: '🏆', category: 'streak', description: '20日連続で学習した', condition: 'streak', threshold: 20 },

  // — Subject —
  { id: 'sub-sansu', name: '算数探検家', icon: '🔢', category: 'subject', description: '算数のユニットを5つクリア', condition: 'math', threshold: 5 },
  { id: 'sub-sugaku', name: '数学探検家', icon: '📐', category: 'subject', description: '数学のユニットを5つクリア', condition: 'math', threshold: 5 },
  { id: 'sub-kokugo', name: '国語名人', icon: '📖', category: 'subject', description: '国語のユニットを5つクリア', condition: 'japanese', threshold: 5 },
  { id: 'sub-eigo', name: '英語スターター', icon: '🌍', category: 'subject', description: '英語のユニットを5つクリア', condition: 'english', threshold: 5 },
  { id: 'sub-rika', name: '理科ラボ研究員', icon: '🔬', category: 'subject', description: '理科のユニットを5つクリア', condition: 'science', threshold: 5 },
  { id: 'sub-shakai', name: '社会マップマスター', icon: '🗺️', category: 'subject', description: '社会のユニットを5つクリア', condition: 'social', threshold: 5 },

  // — Growth —
  { id: 'growth-hunter', name: 'のびしろハンター', icon: '🌱', category: 'growth', description: 'のびしろユニットを3つ発見', condition: 'growth_units', threshold: 3 },
  { id: 'growth-retry', name: 'まちがい直し名人', icon: '🔄', category: 'growth', description: '間違い直しを5回達成', condition: 'retry_count', threshold: 5 },
  { id: 'growth-grit', name: 'ねばり強さバッジ', icon: '💪', category: 'growth', description: '合計10問に挑戦', condition: 'total_attempts', threshold: 10 },
  { id: 'growth-overcome', name: '苦手克服チャレンジャー', icon: '⭐', category: 'growth', description: 'のびしろ→できるに3ユニット成長', condition: 'growth_to_can_do', threshold: 3 },

  // — Juku —
  { id: 'juku-go', name: '今日も塾へGO', icon: '🏫', category: 'juku', description: '塾に1日通った', condition: 'juku_days', threshold: 1 },
  { id: 'juku-review', name: '塾のあと復習できた', icon: '📝', category: 'juku', description: '塾後に復習を3回実施', condition: 'juku_review', threshold: 3 },
  { id: 'juku-hw', name: '宿題完了スター', icon: '✅', category: 'juku', description: 'ミッションを5回完了', condition: 'missions_completed', threshold: 5 },
];

// ---------------------------------------------------------------------------
// 5. DEFAULT_REWARDS
// ---------------------------------------------------------------------------
export const DEFAULT_REWARDS: Reward[] = [
  { id: 'reward-01', name: '好きなおやつ', badgesRequired: 3, claimed: false },
  { id: 'reward-02', name: '本屋さんで1冊', badgesRequired: 5, claimed: false },
  { id: 'reward-03', name: '家族でカフェ', badgesRequired: 7, claimed: false },
  { id: 'reward-04', name: 'おでかけ', badgesRequired: 10, claimed: false },
  { id: 'reward-05', name: '特別体験', badgesRequired: 20, claimed: false },
];

// ---------------------------------------------------------------------------
// 6. PARENT_COMMENT_TEMPLATES
// ---------------------------------------------------------------------------
export const PARENT_COMMENT_TEMPLATES: string[] = [
  '今日もがんばったね！えらい！',
  'コツコツ続けてるのがすごいよ！',
  '間違えても大丈夫、それがのびしろだよ！',
  'ママ（パパ）も応援してるよ！',
  '昨日よりできることが増えてるね！',
  '集中して取り組めたね、かっこいい！',
  '苦手なところにチャレンジしてえらい！',
  '復習までちゃんとやって素晴らしい！',
  '毎日続けてる姿、尊敬するよ！',
  '自分のペースで大丈夫だよ、一歩ずつね！',
  'バッジが増えてきたね、すごい！',
  'ここまで来たのは努力の証だね！',
];

// ---------------------------------------------------------------------------
// 7. CHARACTER_LINES
// ---------------------------------------------------------------------------
export const CHARACTER_LINES: CharacterLine[] = [
  // — login —
  { id: 'cl-001', trigger: 'login', text: 'おかえり！今日もいっしょにがんばろう！' },
  { id: 'cl-002', trigger: 'login', text: '待ってたよ！今日のクエスト、準備できてるよ！' },
  { id: 'cl-003', trigger: 'login', text: 'やぁ！今日はどの教科からやる？' },
  { id: 'cl-004', trigger: 'login', text: '今日もナビゲートするよ！よろしくね！' },

  // — mission_start —
  { id: 'cl-005', trigger: 'mission_start', text: 'ミッション開始！落ち着いてやればだいじょうぶ！' },
  { id: 'cl-006', trigger: 'mission_start', text: 'さあ、クエストに出発だ！' },
  { id: 'cl-007', trigger: 'mission_start', text: 'いくよ！ひとつずつクリアしていこう！' },
  { id: 'cl-008', trigger: 'mission_start', text: '準備OK？スタート！' },

  // — correct —
  { id: 'cl-009', trigger: 'correct', text: '正解！すごい！その調子！' },
  { id: 'cl-010', trigger: 'correct', text: 'やったね！ばっちりだよ！' },
  { id: 'cl-011', trigger: 'correct', text: 'ピンポーン！大正解！' },
  { id: 'cl-012', trigger: 'correct', text: 'さすが！どんどんいこう！' },
  { id: 'cl-013', trigger: 'correct', text: 'ナイス！自信もっていいよ！' },

  // — incorrect —
  { id: 'cl-014', trigger: 'incorrect', text: 'おしい！でも間違いはのびしろだよ！' },
  { id: 'cl-015', trigger: 'incorrect', text: 'ドンマイ！解説を読んでみよう！' },
  { id: 'cl-016', trigger: 'incorrect', text: 'だいじょうぶ、これを覚えれば次は解けるよ！' },
  { id: 'cl-017', trigger: 'incorrect', text: '間違えるのは成長のチャンス！もう一度チャレンジしよう！' },
  { id: 'cl-018', trigger: 'incorrect', text: 'ここがのびしろポイントだね！復習リストに入れておくよ！' },

  // — streak —
  { id: 'cl-019', trigger: 'streak', text: '連続記録更新中！このまま走り抜けよう！' },
  { id: 'cl-020', trigger: 'streak', text: 'すごいペース！毎日続けてるの、ほんとにえらい！' },
  { id: 'cl-021', trigger: 'streak', text: '継続は力なり！キミならできる！' },
  { id: 'cl-022', trigger: 'streak', text: '連続記録、伸びてるよ！明日も待ってるね！' },

  // — badge —
  { id: 'cl-023', trigger: 'badge', text: 'やった！新しいバッジをゲットしたよ！' },
  { id: 'cl-024', trigger: 'badge', text: 'バッジ獲得おめでとう！コレクションが増えたね！' },
  { id: 'cl-025', trigger: 'badge', text: 'すごい！がんばりが認められたね！' },
  { id: 'cl-026', trigger: 'badge', text: '新バッジ解放！ごほうびも近づいてるよ！' },

  // — complete —
  { id: 'cl-027', trigger: 'complete', text: '今日のミッション、全部クリア！おつかれさま！' },
  { id: 'cl-028', trigger: 'complete', text: 'コンプリート！今日もよくがんばったね！' },
  { id: 'cl-029', trigger: 'complete', text: 'すべてクリア！ゆっくり休んで、明日もがんばろう！' },
  { id: 'cl-030', trigger: 'complete', text: '完了！振り返りも書いてみよう！' },
  { id: 'cl-031', trigger: 'complete', text: 'おつかれさま！今日の成長、しっかり記録したよ！' },
];
